title: Vinay VAIBHAV
description: Postdoctoral Researcher in Physics at the Georg-August-Universität Göttingen (Germany).
show_downloads: false

# Build options
markdown: kramdown
highlighter: rouge

google_analytics: G-ZL5HL03DWH

# Plugins
plugins:
  - jekyll-sitemap
