theme: jekyll-theme-minimal
title: Vinay Vaibhav
description: PhD Candidate in Physics at <a href="https://www.imsc.res.in">Institute of Mathematical Sciences</a>, under the supervision of <a href="https://www.imsc.res.in/pinaki_chaudhuri">Pinaki Chaudhuri</a>.
contact: "vinayphys [at] gmail.com"
show_downloads: false