theme: jekyll-theme-minimal
title: Vinay Vaibhav
description: Senior research fellow in Physics at <a href="https://www.imsc.res.in">Institute of Mathematical Sciences</a> Chennai, India
contact: "vinayphys [at] gmail.com"
show_downloads: false
